title: My Engineering Blog
name: TTABUN
description: AI / Robotics / Japan Exchange Student

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

search: true
breadcrumbs: true
paginate: 5
paginate_path: /page:num/

author:
  name: TTABUN

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/