title: My Engineering Blog
name: Lee Y.W
description: AI / Robotics / Japan Exchange Student
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "default"

search: true
breadcrumbs: true
comments: false
paginate: 5
paginate_path: /page:num/

author:
  name: your_name
  avatar: /assets/profile.jpg


plugins:
  - jekyll-include-cache